// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncsxjgrzltddwzbbatjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jc3hqZ3J6bHRkZHd6YmJhdGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjI5MDQsImV4cCI6MjA3NDAzODkwNH0.782aIPfMTH5xKUpmhMTyjankF_pfwC2g9Dujn5fxZ14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});